apiVersion: v2
appVersion: "2.0.0"
description: Deploy the K8s Hello World Test chart.
name: k8s-hello-world-test
type: application
version: 1.0.0
dependencies:
  - name: common
    version: 25.2.2
    repository: oci://tccr.io/truecharts
