image:
  pullPolicy: IfNotPresent
  repository: hcevan/k8s-hello-world-test
  tag: latest
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000
