{{- define "k8s-hello-world-test.secret" -}}
data:
{{- if .Values.secrets.data }}
{{- range $index, $content := .Values.secrets.data }}
  {{ $index }}: |-
{{- tpl $content $ | b64enc | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}

{{- if .Values.secrets.create -}}
{{- template "common.secret" (list . "k8s-hello-world-test.secret") -}}
{{- end -}}
